# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.89.0
      hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
        args:
        - --args=-json
        - --args=-no-color

  -   repo: https://github.com/terraform-docs/terraform-docs
      rev: "v0.17.0"
      hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]
